const $=s=>document.querySelector(s);let games=[],game,ply=0,busy=false;
async function api(path,body){const r=await fetch(path,{cache:"no-store",...(body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw Error(value.error||"Request failed");return value;}
const position=()=>({game_id:game.game_id,revision:game.revision,expected_ply:game.moves.length});
function notice(text){$("#notice").textContent=text;}
function list(){const target=$("#games");target.replaceChildren();for(const item of games.filter(g=>ChessLibrary.matches(g,$("#search").value,$("#filter").value))){const b=document.createElement("button"),title=document.createElement("strong"),detail=document.createElement("small");title.textContent=`${item.white} — ${item.black}`;detail.textContent=`${new Date(item.created_utc_us/1000).toLocaleString()} · ${item.ply_count} plies · ${item.status} · ${item.result}`;b.append(title,detail);b.onclick=()=>openGame(item.id);target.append(b);}}
async function refresh(){games=await api("/api/games");list();const backups=await api("/api/backups"),select=$("#backups");select.replaceChildren(new Option("Choose a backup…",""));backups.forEach(id=>select.add(new Option(id,id)));}
async function openGame(id){if(busy)return;busy=true;try{game=await api("/api/game/open",{game_id:id});ply=0;render();await details();notice("");}catch(e){notice(e.message);}finally{busy=false;}}
function render(){if(!game)return;const m=game.metadata;$("#title").textContent=`${m.white} — ${m.black}`;for(const k of ["white","black","result","status"])$("#"+k).value=m[k];$("#correct-ply").max=game.moves.length;const rows=$("#moves");rows.replaceChildren();game.moves.forEach((move,i)=>{const row=document.createElement("tr");row.className=ply===i+1?"selected-ply":"";for(const text of [move.ply,move.san,ChessLibrary.interval(move.timing),move.provenance]){const cell=document.createElement("td");cell.textContent=text;row.append(cell);}row.onclick=()=>{ply=i+1;render();};rows.append(row);});const fen=ply?game.moves[ply-1].fen_after:game.initial_fen;const board=$("#replay-board");board.replaceChildren();ChessLibrary.board(fen).forEach((p,i)=>{const cell=document.createElement("div");cell.className=`chess-square ${(Math.floor(i/8)+i%8)%2?"dark":"light"}`;const piece=document.createElement("span"),name=document.createElement("small");piece.textContent=p.symbol;name.textContent=p.name;cell.append(piece,name);board.append(cell);});$("#ply-label").textContent=`${ply}/${game.moves.length}`;$("#previous").disabled=ply===0;$("#next").disabled=ply===game.moves.length;const move=game.moves[ply-1];$("#timing-detail").textContent=move?`${move.san} · ${move.timing.quality} completion timing · elapsed ${ChessLibrary.interval(move.timing)}${move.timing.completion?` · completion ${(move.timing.completion.earliest/1e6).toFixed(2)}–${(move.timing.completion.latest/1e6).toFixed(2)} s after session start`:""}`:"Starting position. First-move elapsed time needs a reliable game-start marker.";plot();}
function plot(){const svg=$("#timing-plot");svg.replaceChildren();svg.setAttribute("viewBox","0 0 700 130");const bounds=game.moves.map(m=>m.timing.elapsed_since_previous);const max=Math.max(1,...bounds.filter(Boolean).map(b=>b.latest));bounds.forEach((b,i)=>{const x=20+660*(i+1)/(bounds.length+1);const n=document.createElementNS("http://www.w3.org/2000/svg",b?"line":"circle");const attrs=b?{x1:x,x2:x,y1:110-90*b.latest/max,y2:110-90*b.earliest/max,stroke:"#267456","stroke-width":4}:{cx:x,cy:117,r:2,fill:"#b1895b"};for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);const title=document.createElementNS(n.namespaceURI,"title");title.textContent=`Ply ${i+1}: ${ChessLibrary.interval(game.moves[i].timing)}`;n.append(title);svg.append(n);});}
async function details(){const[evidence,audit]=await Promise.all([api("/api/game/evidence"),api("/api/game/audit")]);$("#audit").textContent=JSON.stringify(audit,null,2);const target=$("#evidence");target.replaceChildren();$("#evidence-status").textContent=evidence.length?`${evidence.length} saved frames; ${evidence.filter(e=>!e.available).length} unavailable. Native evidence retention is limited to 512 MiB.`:"No saved camera evidence for this game. Browser-only recordings do not retain photos.";for(const e of evidence){const f=document.createElement("figure"),caption=document.createElement("figcaption");caption.textContent=`${e.record.kind} · ${(e.record.capture_time_us/1e6).toFixed(2)} s · ${e.available?"available":"missing or changed"}`;if(e.available){const a=document.createElement("a"),img=document.createElement("img");a.href=`/api/evidence/${e.record.id}.jpg`;a.target="_blank";img.src=a.href;img.alt=caption.textContent;a.append(img);f.append(a);}f.append(caption);target.append(f);}}
async function mutate(path,body){if(!game||busy)return false;busy=true;try{game=await api(path,{...position(),...body});ply=Math.min(ply,game.moves.length);render();await details();await refresh();notice(game.first_invalid_ply?`Stopped at invalid ply ${game.first_invalid_ply}. The original suffix is preserved in the audit.`:"Saved.");return true;}catch(e){notice(e.message);return false;}finally{busy=false;}}
$("#save").onclick=()=>mutate("/api/game/metadata",Object.fromEntries(["white","black","result","status"].map(k=>[k,$("#"+k).value])));
$("#correct").onclick=()=>mutate("/api/game/correct",{replace_from_ply:Number($("#correct-ply").value),uci:$("#correct-uci").value.trim(),reason:$("#correct-reason").value.trim()});
$("#resume").onclick=async()=>{if(!game)return;const saved=await mutate("/api/game/metadata",{white:game.metadata.white,black:game.metadata.black,result:game.metadata.result,status:"recording"});if(saved)location.href="/?native=1";};
$("#previous").onclick=()=>{ply=Math.max(0,ply-1);render();};$("#next").onclick=()=>{ply=Math.min(game.moves.length,ply+1);render();};$("#search").oninput=list;$("#filter").onchange=list;
for(const [id,path,ext]of[["pgn","pgn","pgn"],["annotated","pgn-annotated","pgn"],["json","timing.json","json"],["csv","timing.csv","csv"]])$("#"+id).onclick=async()=>{if(!game)return;try{const r=await fetch(`/api/game/${path}`);if(!r.ok)throw Error("Export failed");const url=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=url;a.download=`chess-${game.game_id}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message);}};
$("#backup").onclick=async()=>{try{const value=await api("/api/backup",{});await refresh();notice(`Backup saved: ${value.path}\nRestore into a new data folder with: chess-camera-recorder restore BACKUP_FOLDER NEW_DATA_FOLDER`);}catch(e){notice(e.message);}};
refresh().then(()=>{if(games.length)openGame(games[0].id);}).catch(e=>notice(e.message));

$("#restore").onclick=async()=>{const backup_id=$("#backups").value;if(!backup_id||busy)return;busy=true;try{game=await api("/api/restore",{backup_id});ply=0;render();await details();await refresh();notice("Restored into a new profile. The previous data folder is preserved.");}catch(e){notice(e.message);}finally{busy=false;}};
